//
// Created by tosiek on 21.02.2022.
//

#ifndef AGES1_BATTLE_H
#define AGES1_BATTLE_H

enum Type{SWORD_MAN,BOW_MAN,SPEAR_MAN,HEAVY_CAVALRY,LIGHT_CAVALRY,KNIGHT,CROSSBOWMAN,BILLMAN,AXEMAN};

#endif //AGES1_BATTLE_H
